### ISSUE TITLE
Howlong bug

### ISSUE THREAD

**Issue by phschon** [phschon/ultrabot#26]
@00SteinsGate00 
Entering `!howlong tomb raider` yields the following stack trace:

future: <Task finished coro=<Howlongtobeat.execute() done, defined at /home/elazar/discordbot/plugins/howlongtobeat.py:33> exception=HTTPException('BAD REQUEST (status code: 400)',)>
Traceback (most recent call last):
  File "/home/elazar/discordbot/plugins/howlongtobeat.py", line 63, in execute
    await self.client.send_message(message.channel, response_message)
  File "/home/elazar/discordbot/env/lib/python3.6/site-packages/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "/home/elazar/discordbot/env/lib/python3.6/site-packages/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)

**Comment by j-holub** [comment]
The problem is not really within the **HowLong** plugin, but that `client.send_message()` fails if the message is longer than **2000** characters. This will also happen in other plugins.

I created a pull request to fix this problem for the **HowLong** plugin. But maybe it would be a good idea to create an own send message that already takes care of this problem?
